HEIGHT = 603
WIDTH = 553

TOP_FRAME_HEIGHT = 50
CENTER_FRAME_HEIGHT = 553

CENTER_FRAME_Y_POS = HEIGHT - CENTER_FRAME_HEIGHT

TOP_COLOR = "black"
CENTER_COLOR = "gray"

PLAY_BUTTON_X = (WIDTH/2) - 20
PLAY_BUTTON_Y = 10

LEFT_LABEL_X = (WIDTH/4) - 50
LEFT_LABEL_Y = 3

RIGHT_LABEL_X = (WIDTH-(WIDTH/4)) - 20
RIGHT_LABEL_Y = 3


GRID_ROWS = 16
GRID_COLS = 16
CELL_COUNT = GRID_ROWS * GRID_COLS
MINES_COUNT = 40


BTN_SIZE = 28

CELL_HEIGHT = 28
CELL_WIDTH = 28


FONT_PATH = "fonts/alarm_clock.ttf"
